version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build application
          command: npm run build

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    docker:
      - image: circleci/node:10.15-stretch

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Run static analysis and check code style
          command: npm run lint

workflows:
  version: 2
  build-test-check:
    jobs:
      - build
      - test:
          requires:
            - build

