version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build application
          command: npm run build

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    docker:
      - image: circleci/node:10.15-stretch

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run static analysis and check code style
          command: npm run lint
      - run:
          name: Run tests with coverage check
          command: npm run test:coverage
      - run:
          name: Run documentation linter
          command: npm run lint:docs
      - run:
          name: Verify if documentation is up-to-date
          command: npm run test:docs

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
