version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10.15-stretch
  working_directory: ~/repo

jobs:
  build-test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build application
          command: npm run build

      - run:
          name: Run static analysis and check code style
          command: npm run lint

      - run:
          name: Run tests with coverage check
          command: npm run test:coverage

      - run:
          name: Run documentation linter
          command: npm run lint:docs

      - run:
          name: Verify if documentation is up-to-date
          command: npm run test:docs

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npmjs_token_cosmo" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

