version: 2.1
jobs:
  gh-access:
    docker:
      - image: circleci/node:10.15-stretch

    working_directory: ~/repo

    steps:
      - checkout


workflows:
  version: 2
  gh:
    jobs:
      - gh-access
