apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: node:18.20.4
    resources:
      requests:
        cpu: 0.8
    command:
    - cat
    tty: true
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
